create = "create"
maintain = "maintain"
play = "play"
gamemaster = "gamemaster"
tools = "tools"
about = "about"
mainmenu = "mainmenu"
back = "back"
changelanguage = "changelanguage"
language = "language"
empty = ""

german = "German"
english = "English"

setting_currentLanguage = "CurrentLanguage"
